package sinple;

public class Sym {
  /* terminals */
  public static final int FUNCTION = 14;
  public static final int INCREMENT = 18;
  public static final int MULT = 25;
  public static final int GE = 15;
  public static final int CONCAT = 7;
  public static final int ARRAY = 3;
  public static final int MINUS = 24;
  public static final int DECREMENT = 8;
  public static final int SEMICOLON = 37;
  public static final int NOT = 27;
  public static final int AND = 2;
  public static final int LT = 23;
  public static final int OR = 29;
  public static final int COMMA = 6;
  public static final int LITERALINTERPOLEDSTRING = 43;
  public static final int FUNCTIONIDENT = 42;
  public static final int DIV = 9;
  public static final int PLUS = 30;
  public static final int ASSIGN = 5;
  public static final int IF = 17;
  public static final int LE = 19;
  public static final int EOF = 0;
  public static final int RETURN = 33;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int NULL = 28;
  public static final int NEQ = 26;
  public static final int RIGHTBRACK = 35;
  public static final int EQ = 11;
  public static final int RIGHTPAR = 36;
  public static final int RIGHTBRACE = 34;
  public static final int FOREACH = 13;
  public static final int ELSE = 10;
  public static final int LEFTBRACK = 21;
  public static final int WHILE = 39;
  public static final int LEFTPAR = 22;
  public static final int LEFTBRACE = 20;
  public static final int VARIDENT = 41;
  public static final int LITERALSIMPLESTRING = 44;
  public static final int LITERALINTEGER = 40;
  public static final int REMAINDER = 32;
  public static final int FALSE = 12;
  public static final int AS = 4;
  public static final int GT = 16;
  public static final int PRINT = 31;
  public static final int FOR = 45;
  public static final int DO = 46;  
  public static final int PLUSASSIGN = 47;  
  public static final int MINUSASSIGN = 48;  
  public static final int MULTASSIGN = 49;  
  public static final int DIVASSIGN = 50;  
  public static final int REMAINDERASSIGN = 51;  
  public static final int CONCATASSIGN = 52;
  public static final int SWITCH = 53;
  public static final int CASE = 54;
  public static final int COLON = 55;
  public static final int DEFAULT = 56;      
  public static final int BREAK = 57;
  public static final int CONTINUE = 58;      
  public static final int READ = 59;      
  public static final int READLN = 60;  
  public static final int PRINTLN = 61;  
}

